[
  {
    adult: false,
    backdrop_path: "/79bJL9ydAMYVltuNTt4VhxORqIz.jpg",
    genre_ids: [12, 878],
    id: 329,
    original_language: "en",
    original_title: "Jurassic Park",
    overview:
      "A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA. Before opening day, he invites a team of experts and his two eager grandchildren to experience the park and help calm anxious investors. However, the park is anything but amusing as the security systems go off-line and the dinosaurs escape.",
    popularity: 32.519,
    poster_path: "/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg",
    release_date: "1993-06-11",
    title: "Jurassic Park",
    video: false,
    vote_average: 7.949,
    vote_count: 16072,
  },
  {
    adult: false,
    backdrop_path: "/nhDuyB0H7SPAWtIFrziIMihgRn3.jpg",
    genre_ids: [99],
    id: 995456,
    original_language: "en",
    original_title:
      "Jurassic Greatest Moments: Jurassic Park to Jurassic World",
    overview:
      'Join the cast of "Jurassic World Dominion" as they relive their favorite unforgettable, action-packed and epic moments from the "Jurassic World" franchise.',
    popularity: 10.263,
    poster_path: "/tPdsrxdJBBIvJi5rwcnYGUoPAai.jpg",
    release_date: "2022-06-04",
    title: "Jurassic Greatest Moments: Jurassic Park to Jurassic World",
    video: false,
    vote_average: 6.278,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: "/ozIhpAb69vQahq5obDlRGP87Y0m.jpg",
    genre_ids: [99, 28, 12, 53],
    id: 503210,
    original_language: "en",
    original_title: "Return to Jurassic Park",
    overview:
      "A multi-part documentary about the making of the Jurassic Park trilogy. Each part walks through the making of part of one of the films, including the hurricane during the shooting of the first film, and how advances in CGI for Jurassic Park helped change the world of special effects forever. All interviews for these retrospective documentaries come with comments from Spielberg, Johnston, Neill, Dern, Goldblum, the effects crews, the child actors, and Peter Stormare. This documentary is broken into six parts: Dawn of a New Era (25 min), Making Prehistory (20 min), The Next Step in Evolution (15 min), Finding the Lost World (28 min), Something Survived (16 min), and The Third Adventure (25 min).",
    popularity: 29.41,
    poster_path: "/mPyu59cDdmMDDW9IOtfjVlM0THd.jpg",
    release_date: "2011-02-05",
    title: "Return to Jurassic Park",
    video: false,
    vote_average: 6.603,
    vote_count: 828,
  },
  {
    adult: false,
    backdrop_path: "/uLcs6T07AvtfqIhhvk9j1ugwXU9.jpg",
    genre_ids: [99],
    id: 150354,
    original_language: "en",
    original_title: "The Making of 'Jurassic Park'",
    overview:
      'This documentary treats film fans to a behind-the-scenes look at the making of "Jurassic Park," one of the 90\'s biggest hits and a milestone in special effects development. Narrated by James Earl Jones, it includes footage of the filming process, as well as interviews with director Steven Spielberg, and other members of the cast and crew, who give their insights into what it was like working together on this project and the efforts it took to bring the film to completion.',
    popularity: 9.314,
    poster_path: "/kYVJCtAOhkIbz4MWulx0N17ZNTQ.jpg",
    release_date: "1995-04-23",
    title: "The Making of 'Jurassic Park'",
    video: false,
    vote_average: 7.079,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [27, 878],
    id: 1187166,
    original_language: "en",
    original_title: "Jurassic Park - Found Footage: Outpost B",
    overview:
      "An Jurassic Park worker investigates a power outage at Outpost B.",
    popularity: 2.507,
    poster_path: "/hKR6SGdpLMQz9KmhwiX7Cd9UUr0.jpg",
    release_date: "2023-09-25",
    title: "Jurassic Park - Found Footage: Outpost B",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [12, 28],
    id: 496276,
    original_language: "en",
    original_title: "Jurassic Park: Island Survival",
    overview:
      'Isla Nublar, 2005. Approx. 120 miles off the coast of Costa Rica, 87 miles away from Isla Sorna. "There are several paleontologist missing on Isla Nublar. They had an expedition to explore and excavate the island for bone samples from several dinosaurs for extracting DNA sequences. Other important mission is to find the missing embryos from the Barbasol Cryogenics Can. On behalf of Simon Masrani, the science research team had to find out where those specimens are and have to check some important documents at the abandoned foliaged InGen Reseach Compound, which is decaying and overrun with vines deep in the dense afforestation now.',
    popularity: 3.613,
    poster_path: "/e3EU9PG7KslTVVgj0CiGJXi3PUG.jpg",
    release_date: "",
    title: "Jurassic Park: Island Survival",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [878, 12, 28, 53, 99],
    id: 516058,
    original_language: "en",
    original_title: "Beyond Jurassic Park",
    overview:
      "Prepare to go deeper into the breathtaking adventures of the Jurassic Park Trilogy!  Highlighted by fascinating, never-seen-before footage from all three Jurassic Park films, this DVD offers an exclusive look at deleted scenes, additional footage and other materials not shown on any theater screen.",
    popularity: 4.383,
    poster_path: "/r5KUlQ0mq4HUcuqog8gzIBYtW0C.jpg",
    release_date: "2001-01-01",
    title: "Beyond Jurassic Park",
    video: false,
    vote_average: 6.7,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: "/9soME6xONQnG0gVo0qgNjSp3gJZ.jpg",
    genre_ids: [16, 35],
    id: 1171423,
    original_language: "en",
    original_title: "LEGO Jurassic Park: The Unofficial Retelling",
    overview:
      "After finding his journal, Chaos Mathematician Dr. Ian Malcolm recalls the mishaps and mayhem from 30 years ago about the island amusement park filled with prehistoric dinosaurs who escape and run amok...",
    popularity: 6.411,
    poster_path: "/xSq8TrEqz8NRyWJSviteKE1t249.jpg",
    release_date: "2023-10-10",
    title: "LEGO Jurassic Park: The Unofficial Retelling",
    video: false,
    vote_average: 6.1,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: "/s7bq80peqy9fA9VLZM1Snm2uqwP.jpg",
    genre_ids: [878, 12, 28],
    id: 1293794,
    original_language: "en",
    original_title: "Jurassic Park: Prime Survival",
    overview:
      "They shouldn’t be there. They shouldn’t have come. Now they have to survive. When a group of three friends head to a deserted island, little do they know that they are about to stumble on something very big, and very dangerous.",
    popularity: 5.096,
    poster_path: "/t2FN68cioXwlLhFG5zyY3CfJ0Ox.jpg",
    release_date: "2011-04-08",
    title: "Jurassic Park: Prime Survival",
    video: false,
    vote_average: 4,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/w9eBtIHHpGgGfjqnEAJM3s7mCOa.jpg",
    genre_ids: [12, 28, 878],
    id: 330,
    original_language: "en",
    original_title: "The Lost World: Jurassic Park",
    overview:
      "Four years after Jurassic Park's genetically bred dinosaurs ran amok, multimillionaire John Hammond shocks chaos theorist Ian Malcolm by revealing that he has been breeding more beasties at a secret location. Malcolm, his paleontologist ladylove and a wildlife videographer join an expedition to document the lethal lizards' natural behavior in this action-packed thriller.",
    popularity: 2.644,
    poster_path: "/jElpCJkSaRPYwIMwZY28gOKV7BK.jpg",
    release_date: "1997-05-23",
    title: "The Lost World: Jurassic Park",
    video: false,
    vote_average: 6.536,
    vote_count: 8227,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 331984,
    original_language: "en",
    original_title: "The Real Jurassic Park",
    overview:
      "Could scientists recreate Hollywood's Jurassic Park using 100-million-year-old dinosaur DNA? Director Steven Spielberg, author Michael Crichton, actor Jeff Goldblum, and a host of scientific experts answer this compelling question in the award-winning Nova documentary, The Real Jurassic Park. Behind-the-scenes clips, interviews, and demonstrations with leading paleontologists investigate the viability of reviving the extinct species. All phases of logistics are addressed, including extracting prehistoric insect DNA, creating embryos for placement in host eggs, and more. The scientific analysis of the process leads to the examination of the ethics of recreating a vanished life form.",
    popularity: 1.555,
    poster_path: "/vdH1Gk5V5R9cXILsoLmYol6OYLW.jpg",
    release_date: "1993-11-09",
    title: "The Real Jurassic Park",
    video: false,
    vote_average: 6,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 1200709,
    original_language: "en",
    original_title: "The Making Of  'Jurassic Park III'",
    overview:
      "A very in depth look at the making of the movie, a look at the special effects and animatronics made for the motion picture, Jurassic Park III (2001). Interviews with the cast and crew give us a sneak peek at the film. The movie used many different new dinosaurs compared to the first two films, here they examine how they'll look in the final product",
    popularity: 3.86,
    poster_path: "/f32yN9f8AFFgp6k8N5MQ3mvTXAT.jpg",
    release_date: "2001-12-11",
    title: "The Making Of  'Jurassic Park III'",
    video: true,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/hc0rX4AjWy4N39ByuXKbnhjbFia.jpg",
    genre_ids: [12, 28, 53, 878],
    id: 331,
    original_language: "en",
    original_title: "Jurassic Park III",
    overview:
      "In need of funds for research, Dr. Alan Grant accepts a large sum of money to accompany Paul and Amanda Kirby on an aerial tour of the infamous Isla Sorna. It isn't long before all hell breaks loose and the stranded wayfarers must fight for survival as a host of new -- and even more deadly -- dinosaurs try to make snacks of them.",
    popularity: 2.256,
    poster_path: "/oQXj4NUfS3r3gHXtDOzcJgj1lLc.jpg",
    release_date: "2001-07-18",
    title: "Jurassic Park III",
    video: false,
    vote_average: 6.137,
    vote_count: 7010,
  },
  {
    adult: false,
    backdrop_path: "/698FjyzLdpgXmUSr63LaRwblTmx.jpg",
    genre_ids: [12, 28, 878],
    id: 507086,
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators ona planet they now share with history's most fearsome creatures.",
    popularity: 126.832,
    poster_path: "/i74yGY5QMgq6seceDhltaPJ0xfO.jpg",
    release_date: "2022-06-01",
    title: "Jurassic World Dominion",
    video: false,
    vote_average: 6.7,
    vote_count: 5938,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 349071,
    original_language: "en",
    original_title: "Jurassic Park HS",
    overview:
      'Every quarter century or so a project comes along that so perfectly unites artist and medium that one can only stand in wonder and proclaim, "Wow, Sandra, when was the last time something this magical came along - quarter century or so, wasn\'t it?"  So it was with Michelangelo and marble; Paderewsky and piano; And so it is with this RiffTrax, uniting THE legendary dinosaur movie of our time and THE weirdest "Weird Al" Yankovic of our time into one harmonic convergence of RiffTastic Jurassic WeirdAlistic bliss!',
    popularity: 1.865,
    poster_path: null,
    release_date: "",
    title: "Jurassic Park HS",
    video: false,
    vote_average: 4.9,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 1039574,
    original_language: "en",
    original_title: "Jurassic Park III: A Visit To ILM",
    overview:
      "A look at the wizardry of ILM in creating the visual effects of JP III featuring interviews with the VFX artists explaining their techniques. Consisting of 4 parts, Concepts, Process, Muscle Simulation and Composting.",
    popularity: 1.53,
    poster_path: null,
    release_date: "2001-12-11",
    title: "Jurassic Park III: A Visit To ILM",
    video: true,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/dF6FjTZzRTENfB4R17HDN20jLT2.jpg",
    genre_ids: [28, 12, 878, 53],
    id: 135397,
    original_language: "en",
    original_title: "Jurassic World",
    overview:
      "Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
    popularity: 76.264,
    poster_path: "/A0LZHXUzo5C60Oahvt7VxvwuzHw.jpg",
    release_date: "2015-06-06",
    title: "Jurassic World",
    video: false,
    vote_average: 6.7,
    vote_count: 20151,
  },
  {
    adult: false,
    backdrop_path: "/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg",
    genre_ids: [28, 12, 878, 53],
    id: 351286,
    original_language: "en",
    original_title: "Jurassic World: Fallen Kingdom",
    overview:
      "Three years after Jurassic World was destroyed, Isla Nublar now sits abandoned. When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.",
    popularity: 74.953,
    poster_path: "/x8cLgs0uXlb9rmpuVIxopoRGnCr.jpg",
    release_date: "2018-06-06",
    title: "Jurassic World: Fallen Kingdom",
    video: false,
    vote_average: 6.5,
    vote_count: 11629,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 1252229,
    original_language: "en",
    original_title: "Jurassic park (YouTube Short)",
    overview: "An honest depiction",
    popularity: 0.911,
    poster_path: null,
    release_date: "2022-07-27",
    title: "Jurassic park (YouTube Short)",
    video: true,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 1282633,
    original_language: "en",
    original_title: "Jurassic Park - Found Footage: Containment Operation",
    overview:
      '"Analog Horror has been viral for a few years on the internet. It is a mix of 80/90s esthetics and subtle horror, based on tense situation and feeling of loneliness. There are many creators dedicating this style to the Jurassic Park franchise and I thought it would be fun to be a part of it."',
    popularity: 1.067,
    poster_path: "/3XkiJJbVG5wXvHGqcMqscsg96c4.jpg",
    release_date: "2024-02-17",
    title: "Jurassic Park - Found Footage: Containment Operation",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/jNjT5y95BToczcxgVPl1NBB7goY.jpg",
    genre_ids: [12, 28, 878],
    id: 11,
    original_language: "en",
    original_title: "Star Wars",
    overview:
      "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
    popularity: 100.434,
    poster_path: "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    release_date: "1977-05-25",
    title: "Star Wars",
    video: false,
    vote_average: 8.2,
    vote_count: 20365,
  },
  {
    adult: false,
    backdrop_path: "/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg",
    genre_ids: [12, 28, 878],
    id: 140607,
    original_language: "en",
    original_title: "Star Wars: The Force Awakens",
    overview:
      "Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.",
    popularity: 65.862,
    poster_path: "/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg",
    release_date: "2015-12-15",
    title: "Star Wars: The Force Awakens",
    video: false,
    vote_average: 7.276,
    vote_count: 19159,
  },
  {
    adult: false,
    backdrop_path: "/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg",
    genre_ids: [12, 28, 878],
    id: 181808,
    original_language: "en",
    original_title: "Star Wars: The Last Jedi",
    overview:
      "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
    popularity: 97.655,
    poster_path: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
    release_date: "2017-12-13",
    title: "Star Wars: The Last Jedi",
    video: false,
    vote_average: 6.797,
    vote_count: 15075,
  },
  {
    adult: false,
    backdrop_path: "/jn52me8AagfNt7r84SgQbV0R9ZG.jpg",
    genre_ids: [12, 28, 878],
    id: 181812,
    original_language: "en",
    original_title: "Star Wars: The Rise of Skywalker",
    overview:
      "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
    popularity: 82.868,
    poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
    release_date: "2019-12-18",
    title: "Star Wars: The Rise of Skywalker",
    video: false,
    vote_average: 6.322,
    vote_count: 9736,
  },
  {
    adult: false,
    backdrop_path: "/ojHCeDULAkQK25700fhRU75Tur2.jpg",
    genre_ids: [878, 12, 28],
    id: 348350,
    original_language: "en",
    original_title: "Solo: A Star Wars Story",
    overview:
      "Through a series of daring escapades deep within a dark and dangerous criminal underworld, Han Solo meets his mighty future copilot Chewbacca and encounters the notorious gambler Lando Calrissian.",
    popularity: 43.86,
    poster_path: "/4oD6VEccFkorEBTEDXtpLAaz0Rl.jpg",
    release_date: "2018-05-15",
    title: "Solo: A Star Wars Story",
    video: false,
    vote_average: 6.561,
    vote_count: 8383,
  },
  {
    adult: false,
    backdrop_path: "/iflKt34Ck2JpY2PY9wW1zwdJgJi.jpg",
    genre_ids: [16, 878, 12, 10751],
    id: 782054,
    original_language: "ja",
    original_title: "映画ドラえもん のび太の宇宙小戦争 2021",
    overview:
      "One day during summer vacation, a palm-sized alien named Papi appears from a small rocket that Nobita picks up. He is the president of Pirika, a small planet in outer space, and has come to Earth to escape the rebels. Doraemon and his friends are puzzled by Papi’s small size, but as they play together using the secret tool “Small Light”, they gradually become friends. However, a whale-shaped space battleship comes to earth and attacks Doraemon, Nobita and the others in order to capture Papi. Feeling responsible for getting everyone involved, Papi tries to stand up to the rebels. Doraemon and his friends leave for the planet Pirika to protect their dear friend and his home.",
    popularity: 21.633,
    poster_path: "/48gKZioIDeUOI0afbYv3kh9u9RQ.jpg",
    release_date: "2022-03-04",
    title: "Doraemon the Movie: Nobita's Little Star Wars 2021",
    video: false,
    vote_average: 5.9,
    vote_count: 106,
  },
  {
    adult: false,
    backdrop_path: "/3TeGmKJfkik1D1rIoqGb1aR4k9c.jpg",
    genre_ids: [12, 28, 878],
    id: 1893,
    original_language: "en",
    original_title: "Star Wars: Episode I - The Phantom Menace",
    overview:
      "Anakin Skywalker, a young slave strong with the Force, is discovered on Tatooine. Meanwhile, the evil Sith have returned, enacting their plot for revenge against the Jedi.",
    popularity: 46.608,
    poster_path: "/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
    release_date: "1999-05-19",
    title: "Star Wars: Episode I - The Phantom Menace",
    video: false,
    vote_average: 6.553,
    vote_count: 14405,
  },
  {
    adult: false,
    backdrop_path: "/8mTHUXS3vwub5ZlovQkZ8veQUah.jpg",
    genre_ids: [28, 12, 878],
    id: 330459,
    original_language: "en",
    original_title: "Rogue One: A Star Wars Story",
    overview:
      "A rogue band of resistance fighters unite for a mission to steal the Death Star plans and bring a new hope to the galaxy.",
    popularity: 45.048,
    poster_path: "/i0yw1mFbB7sNGHCs7EXZPzFkdA1.jpg",
    release_date: "2016-12-14",
    title: "Rogue One: A Star Wars Story",
    video: false,
    vote_average: 7.493,
    vote_count: 15056,
  },
  {
    adult: false,
    backdrop_path: "/f53Jujiap580mgfefID0T0g2e17.jpg",
    genre_ids: [16, 10751, 878, 35, 10770],
    id: 857702,
    original_language: "en",
    original_title: "LEGO Star Wars Terrifying Tales",
    overview:
      "Poe Dameron and BB-8 must face the greedy crime boss Graballa the Hutt, who has purchased Darth Vader’s castle and is renovating it into the galaxy’s first all-inclusive Sith-inspired luxury hotel.",
    popularity: 19.296,
    poster_path: "/fYiaBZDjyXjvlY6EDZMAxIhBO1I.jpg",
    release_date: "2021-10-01",
    title: "LEGO Star Wars Terrifying Tales",
    video: false,
    vote_average: 6.815,
    vote_count: 241,
  },
  {
    adult: false,
    backdrop_path: "/5vDuLrjJXFS9PTF7Q1xzobmYKR9.jpg",
    genre_ids: [12, 28, 878],
    id: 1895,
    original_language: "en",
    original_title: "Star Wars: Episode III - Revenge of the Sith",
    overview:
      "The evil Darth Sidious enacts his final plan for unlimited power -- and the heroic Jedi Anakin Skywalker must choose a side.",
    popularity: 45.884,
    poster_path: "/xfSAoBEm9MNBjmlNcDYLvLSMlnq.jpg",
    release_date: "2005-05-17",
    title: "Star Wars: Episode III - Revenge of the Sith",
    video: false,
    vote_average: 7.432,
    vote_count: 13520,
  },
  {
    adult: false,
    backdrop_path: "/abwxHfymXGAbbH3lo9PDEJEfvtW.jpg",
    genre_ids: [12, 28, 878],
    id: 1894,
    original_language: "en",
    original_title: "Star Wars: Episode II - Attack of the Clones",
    overview:
      "Following an assassination attempt on Senator Padmé Amidala, Jedi Knights Anakin Skywalker and Obi-Wan Kenobi investigate a mysterious plot that could change the galaxy forever.",
    popularity: 41.784,
    poster_path: "/oZNPzxqM2s5DyVWab09NTQScDQt.jpg",
    release_date: "2002-05-15",
    title: "Star Wars: Episode II - Attack of the Clones",
    video: false,
    vote_average: 6.567,
    vote_count: 13047,
  },
  {
    adult: false,
    backdrop_path: "/wBBONMlfnrU2GxxN7X2pFDdZuRB.jpg",
    genre_ids: [16, 12, 10751, 14, 878],
    id: 161704,
    original_language: "ja",
    original_title: "ドラえもん のび太の宇宙小戦争",
    overview:
      "Nobita helps Doraemon to create a space movie. After Dekisugi fails to help them, the duo rope in Shizuka, who prefers to make a film about dolls.",
    popularity: 14.5,
    poster_path: "/n4IPqrfXEEtMC8hzV5PaCElkdNP.jpg",
    release_date: "1985-03-16",
    title: "Doraemon: Nobita's Little Star Wars",
    video: false,
    vote_average: 6.878,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: "/uNjBnOmdjZoiWTLQ938YJZ1cYVU.jpg",
    genre_ids: [16, 35, 10751, 878, 12, 10770],
    id: 392216,
    original_language: "en",
    original_title: "Phineas and Ferb: Star Wars",
    overview:
      "Phineas and Ferb become the galaxy's unlikeliest last hope when they must return the Death Star plans to the Rebel Alliance.",
    popularity: 16.228,
    poster_path: "/2XGlp5x232CeZM0PVjMMYQcXViA.jpg",
    release_date: "2014-07-26",
    title: "Phineas and Ferb: Star Wars",
    video: false,
    vote_average: 7.153,
    vote_count: 199,
  },
  {
    adult: false,
    backdrop_path: "/1Lhc32P0a62BgMFgd20wXR1osR3.jpg",
    genre_ids: [16, 10751, 878, 12, 35],
    id: 732670,
    original_language: "en",
    original_title: "LEGO Star Wars Holiday Special",
    overview:
      "As her friends prep for a Life Day holiday celebration, Rey journeys with BB-8 on a quest to gain a deeper knowledge of the Force at a mysterious Jedi Temple. There, she embarks on a cross-timeline adventure through beloved moments in Star Wars history, coming into contact with iconic heroes and villains from all eras of the saga. But will she make it back in time for the Life Day feast?",
    popularity: 12.875,
    poster_path: "/zyzJSI7UZZzz5Toj10rYGF5689z.jpg",
    release_date: "2020-11-17",
    title: "LEGO Star Wars Holiday Special",
    video: false,
    vote_average: 6.529,
    vote_count: 314,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 432134,
    original_language: "en",
    original_title: "Star Wars: Heroes & Villains",
    overview:
      "A look at the creation and filming of the various heroes and villains from all six Star Wars movies, leading up to the release of Star Wars: Episode III - Revenge of the Sith.",
    popularity: 3.408,
    poster_path: "/9ReI6qt3bvsIxUZkDpOzaCpiLwx.jpg",
    release_date: "2005-05-03",
    title: "Star Wars: Heroes & Villains",
    video: false,
    vote_average: 7.2,
    vote_count: 20,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 522640,
    original_language: "es",
    original_title: "Criaturas de La guerra de las galaxias",
    overview: "",
    popularity: 4.697,
    poster_path: null,
    release_date: "2006-12-12",
    title: "Creatures from Star Wars",
    video: false,
    vote_average: 4,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/l3OSKCM0oBOGuioC2jeaeeV8m4I.jpg",
    genre_ids: [16, 35, 878, 28, 10770],
    id: 42979,
    original_language: "en",
    original_title: "Robot Chicken: Star Wars",
    overview:
      "A series of 30 sketches, following the hilarious antics of various characters from a galaxy, far, far away.",
    popularity: 10.152,
    poster_path: "/h44WN4mVJ6wEpJgLaaNoFjv0NAo.jpg",
    release_date: "2007-07-17",
    title: "Robot Chicken: Star Wars",
    video: false,
    vote_average: 7.222,
    vote_count: 243,
  },
  {
    adult: false,
    backdrop_path: "/98CXGiN2bIh6HUnRjFNGgA9o4FZ.jpg",
    genre_ids: [99],
    id: 956879,
    original_language: "fr",
    original_title: "Dans l’ombre du Star Wars Kid",
    overview:
      "Ghyslain Raza, better known as the “Star Wars Kid,” breaks his silence to reflect on our hunger for content and the right to be forgotten in the digital age.",
    popularity: 2.292,
    poster_path: "/zspMlOFJ76g5KyfmucgnvnkJnuN.jpg",
    release_date: "2022-03-30",
    title: "Star Wars Kid: The Rise of the Digital Shadows",
    video: false,
    vote_average: 7.6,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: "/eVA4ztLIuPEsokkgQ3NRt9rTRVh.jpg",
    genre_ids: [16, 28, 878, 12],
    id: 12180,
    original_language: "en",
    original_title: "Star Wars: The Clone Wars",
    overview:
      "As the Clone Wars sweep through the galaxy, the heroic Jedi Knights struggle to maintain order and restore peace. More and more systems are falling prey to the forces of the dark side as the Galactic Republic slips further and further under the sway of the Separatists and their never-ending droid army. Anakin Skywalker and his Padawan learner Ahsoka Tano find themselves on a mission with far-reaching consequences, one that brings them face-to-face with crime lord Jabba the Hutt. But Count Dooku and his sinister agents, including the nefarious Asajj Ventress, will stop at nothing to ensure that Anakin and Ahsoka fail at their quest. Meanwhile, on the front lines of the Clone Wars, Obi-Wan Kenobi and Master Yoda lead the massive clone army in a valiant effort to resist the forces of the dark side...",
    popularity: 22.11,
    poster_path: "/iJQfixW818LUdSXlCDL3JZm0S0g.jpg",
    release_date: "2008-08-05",
    title: "Star Wars: The Clone Wars",
    video: false,
    vote_average: 6.126,
    vote_count: 1968,
  },
  {
    adult: false,
    backdrop_path: "/7nHXstkbnX8t7fKICraMJkuPhK5.jpg",
    genre_ids: [14, 878, 10751, 10770],
    id: 74849,
    original_language: "en",
    original_title: "The Star Wars Holiday Special",
    overview:
      "Luke Skywalker and Han Solo battle evil Imperial forces to help Chewbacca reach his imperiled family on the Wookiee planet - in time for Life Day, their most important day of the year!",
    popularity: 15.989,
    poster_path: "/2X17DnEtlI6ULf95wXC6sA4GrlL.jpg",
    release_date: "1978-11-17",
    title: "The Star Wars Holiday Special",
    video: false,
    vote_average: 3.335,
    vote_count: 448,
  },
];
